"""add_measurement_config_table

Revision ID: 980ddeeebd9c
Revises: 54f68ea8a6b5
Create Date: 2025-05-19 12:21:14.431188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '980ddeeebd9c'
down_revision = '54f68ea8a6b5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('measurement_config',
    sa.Column('measurement_frequency', sa.Integer(), nullable=False),
    sa.Column('first_measurement', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rgb_camera', sa.Boolean(), nullable=False),
    sa.Column('multispectral_camera', sa.Boolean(), nullable=False),
    sa.Column('number_of_sensors', sa.Integer(), nullable=False),
    sa.Column('length_of_ae', sa.Float(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_measurement_config'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('measurement_config')
    # ### end Alembic commands ###
